### ISSUE TITLE
not working for amazon azw3

### ISSUE THREAD

**Issue by flgal** [noDRM/DeDRM_tools#619] opened 2024-08-31 21:56 UTC
### Question / bug report

msg: book is locked by DRM
per https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
I have old version of kindle on my windows 10 v.1.17  (it is set to not auto update)
it is synced to my amz acct where the purchased book
i downloaded book to pc - it is azw3
i have calibr 7.17 installed with DeDRm 10.0.9 
i did not put any serial code in deDRM as th book is now in my kindle for pc
opened book in calibre-debug --gui
still would not open - still locked 

### Which version of Calibre are you running?

7.17

### Which version of the DeDRM plugin are you running?

10.0.9 

### If applicable, which version of the Kindle software are you running?

1.17 

### Log output

```log
Paste log output here.
calibre-debug --gui
calibre 7.17  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.11.5
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre-debug.exe
Successfully initialized third party plugins: DeDRM (10, 0, 9)
QPA platform: windows
devicePixelRatio: 1.25
logicalDpi: 96.0 x 96.0
physicalDpi: 65.35075376884421 x 65.31428571428572
ApplicationPaletteChange event ignored
Using calibre Qt style: True
[0.00] Starting up...
[0.02] Showing splash screen...
[1.16] splash screen shown
[1.16] Initializing db...
[1.19] db initialized
[1.19] Constructing main UI...
[1.47] GUI main window shown
[1.50] main UI initialized...
[1.50] Hiding splash screen
[1.50] splash screen hidden
[1.50] Started up in 1.50 seconds with 0 books
stdout+stderr from file dialog helper: [b'', b'']
piped data from file dialog helper: [b'\xa4-s\x0f\xa2\xc2\x81HuvDw4\x01\xac\x0cJ\xce\xb9(\xa1\x17\xb8\xe4j\x8b\x9f\x8e\xbb\xe7\xb4\x12', b'D:\\hhear\\Documents\\# DWNLOADS - Software\\Calibre\\books\\Dennis William Hauck\\Alchemy Workbook_ Exercises in Transformation.azw3']
DeDRM v10.0.9: Trying to decrypt Alchemy Workbook_ Exercises in Transformation.azw3
MobiDeDrm v1.1.
Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Alchemy Workbook: Exercises in Transformation
Found 0 keys to try after 0.6 seconds
Crypto Type is: 2
DeDRM v10.0.9: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v10.0.9: Looking for new default Kindle Key after 0.6 seconds
searching for kinfoFiles in C:\Users\hhear\AppData\Local
Found K4PC 1.9+ kinf2011 file: C:\Users\hhear\AppData\Local\Amazon\Kindle\storage\.kinf2011
Decrypted key file using IDString '3426669216' and UserName 'hhear'
DeDRM v10.0.9: Found 1 new key
MobiDeDrm v1.1.
Copyright © 2008-2022 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Alchemy Workbook: Exercises in Transformation
Got DSN key from database key_0
Found 4 keys to try after 0.7 seconds
Crypto Type is: 2
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\hhear\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\hhear\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 965, in KindleMobiDecrypt
  File "C:\Users\hhear\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\hhear\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
mobidedrm.DrmException: No key found in 4 PIDs tried.
DeDRM v10.0.9: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 931, in KindleMobiDecrypt
  File "C:\Users\hhear\AppData\Roaming\calibre\plugins\DeDRM.zip\k4mobidedrm.py", line 203, in GetDecryptedBook
  File "C:\Users\hhear\AppData\Roaming\calibre\plugins\DeDRM.zip\mobidedrm.py", line 401, in processBook
mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre\customize\ui.py", line 199, in _run_filetype_plugins
  File "calibre_plugins.dedrm.__init__", line 1030, in run
  File "calibre_plugins.dedrm.__init__", line 981, in KindleMobiDecrypt
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.9: Ultimately failed to decrypt after 0.7 seconds. Read the FAQs at noDRM's repository: https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md
Added Alchemy Workbook: Exercises in Transformation to db in: 1.4
Added 1 books in 2.3 seconds
Worker Launch took: 0.00 seconds
Worker Launch took: 0.02 seconds

**Comment by ElleKayEm** [comment] 2024-08-31 22:16
Each app/device has a unique key even if they are logged into the same account.  The key which DeDRM automatically retrieves from Kindle for PC will only work for books downloaded with that installation of Kindle for PC.  If that copy of the book is from or for an E-ink Kindle, then enter that Kindle's serial number into DeDRM's customization.

**Comment by flgal** [comment] 2024-09-01 00:00
Thanks for your reply. Before I started messing with the Kindle for PC App, I had tried it using the kindle serial number for my kindle tablet and that didn't work either. What does this mean, "books downloaded with that installation of Kindle for PC" ? Does this mean that a book I downloaded before I installed Kindle for PC won't work? And how does one go about downloading someting into the Kindle for PC app on my PC?  Does this mean that now I have the Kindle for PC installed I need to download the book again to my PC and if so, does  it go into Calibre files somewhere? Seems like I am missing some steps that need to happen in a specific order.

**Comment by ElleKayEm** [comment] 2024-09-01 00:10
If the book is from or for a Fire tablet, you cannot decrypt that copy of the book.  Download the book with Kindle for PC and add that copy of the book to calibre.

**Comment by flgal** [comment] 2024-09-01 01:30
did that: Download the book with Kindle for PC and add that copy of the book to calibre.
it downloaded as a azw3 file.
still locked

**Comment by ElleKayEm** [comment] 2024-09-01 09:06
Books from Kindle for PC have an azw extension.  The book in your log looks like one that was downloaded from the website.  In Kindle for PC, right-click the book and select download.  Books will be in My Kindle Content inside your Documents folder.

**Comment by flgal** [comment] 2024-09-01 12:59
this is crazy. I have downloaded 10 books from inside the kindle for pc v.1.17, 
found them in my kindle content with file names like: B08T9G9H3F_EBOK.azw,
 imported into calibre and it says it is a azw3 file 
and will not open the book beyond the book cover. 
can't read the books in the reader.
This is the same for all 10 books.

**Comment by ElleKayEm** [comment] 2024-09-01 13:58
If the file extension is now azw3 in calibre and you can open it in the viewer without an error message about DRM, then the book is decrypted.  No idea why you can't turn past the cover.

That particular book which you gave the file name for should already be DRM-free if it was purchased and not borrowed with Kindle Unlimited.

**Comment by flgal** [comment] 2024-09-01 15:02
if that particular bok is already drm free then how come I cannot read it in calibre? - which I can't. LIke I said, NONE of them go beyond the cover page. NONE are readable.

**Comment by ElleKayEm** [comment] 2024-09-01 16:57
Keep scrolling.  Or right click in the viewer and open the table of contents to navigate somewhere past the cover.

**Comment by flgal** [comment] 2024-09-01 17:33
Thanks so much for all your replies but I clicked to show the navigation and there is NONE on any of the books from amazon. This has been a total waste of my time.

**Closed** 2024-09-01 17:33 UTC

**Comment by ElleKayEm** [comment] 2024-09-01 17:48
I don't think the issue is DRM.
