### ISSUE TITLE
Calibre 6.0 w11 dedrm 10.3 does not appear in calibre view obok does but this one does not. Solution ?

### ISSUE THREAD

**Issue by birdybird123** [noDRM/DeDRM_tools#100] opened 2022-07-14 06:39 UTC
Calibre 6.0 w11 dedrm 10.3 does not appear in calibre view obok does but this one does not. Solution ?

**Comment by ElleKayEm** [comment] 2022-07-14 11:00
Can't reproduce this problem.  You can load it, but it doesn't show up in the list of plugins under File Type?  Even after restarting calibre?  Do you have more than one version of calibre installed -- calibre portable or an older 32-bit calibre?

**Comment by birdybird123** [comment] 2022-07-14 12:33
it does show up under plugins but not next to obok
in the view pane.

**Comment by ElleKayEm** [comment] 2022-07-14 12:42
It doesn't appear there.  It works when you add a book to calibre.

**Comment by birdybird123** [comment] 2022-07-14 13:25
where can i find then the view of the plugin. can you add a picture. i cant find it. in the very old days it was next to obok view

**Comment by ElleKayEm** [comment] 2022-07-14 13:44
On the toolbar?  DeDRM hasn't ever appeared there.  If you need to set anything up, select DeDRM in the plugins list and click the customize plugin button.

**Comment by ElleKayEm** [comment] 2022-07-14 15:17
As I said, DeDRM has never appeared on the toolbar.  The only things to see are the settings available from "Customize plugin".  To use the plugin, you simply add a book to calibre either with the Add books button or by dragging and dropping.

**Comment by birdybird123** [comment] 2022-07-14 15:25
Ok thank you for the reply

**Comment by ElleKayEm** [comment] 2022-07-14 15:27
If you're all set, you can close the issue.

**Closed** 2022-07-14 15:41 UTC
