### ISSUE TITLE
Doesn't work with Calibre 6.0

### ISSUE THREAD

**Issue by AxelSkye** [noDRM/DeDRM_tools#96] opened 2022-07-11 11:49 UTC
### Question / bug report

I just upgraded Calibre to version 6. If the DeDRM plugin is enabled I get python files errors when trying to import any epub.

### Which version of Calibre are you running?

6.0

### Which version of the DeDRM plugin are you running?

v10.0.2

### Log output

```log
 Worker process crashed while executing job Traceback (most recent call last):
File "calibre/utils/ipc/pool.py", line 108, in recv
File "calibre/utils/ipc/__init__.py", line 24, in eintr_retry_call
File "multiprocessing/connection.py", line 221, in recv_bytes
File "multiprocessing/connection.py", line 419, in _recv_bytes
File "multiprocessing/connection.py", line 388, in _recv EOFError```

**Comment by bestlem** [comment] 2022-07-11 12:19
See #54

**Comment by JSWolf** [comment] 2022-07-12 09:12
The reason for this problem is that DeDRM is trying to load the Apple supplied libcrypto instead of the Calibre supplied libcrypto. The solution can be found on Mobileread in the following post written by kovidgoyal (author of Calibre).

https://www.mobileread.com/forums/showpost.php?p=4237911&postcount=74

**Comment by jwilker** [comment] 2022-07-12 18:14
It might be out of scope, but for a moderately capable person, which file would require tweaking? I did some searches of the contents of the zip file but couldn't figure it out. I assume that's where we'd make the change, before adding to Calibre?

This is my first time attempting anything like this, so maybe out of my depth, but willing to try :)

**Comment by MattieGit** [comment] 2022-07-12 20:40
> NM I got it. Building a release from master does solve the issue. Two ADE epubs imported fine.

Do you mind sharing the high-level steps you took to build this release from master? Thanks a lot!

**Comment by agentxan** [comment] 2022-07-12 20:54
If you are signed in to github then you can download a zip file that is built from the latest commit by clicking on the Actions tab. Then click on the top workflow listed which right now is "fix the regular expression". Then at the bottom of the page under Artifacts there is a plugin zip that you can download. The plugin.zip that is downloaded contains DeDRM_tools.zip that you then unzip to get the latest plugins

**Comment by MattieGit** [comment] 2022-07-13 07:34
Many thanks! Done and works flawlessly!

**Comment by chrisboeg** [comment] 2022-07-13 10:44
As far as I can see, the problem with importing epubs with DeDRM has been resolved, but the issue with `AttributeError: type object 'QTableWidgetItem' has no attribute 'UserType'` mentioned [here](https://github.com/apprenticeharper/DeDRM_tools/issues/2092) is still not solved. Others having the same experience?

**Comment by agentxan** [comment] 2022-07-13 12:27
If you make the following changes it works for me on windows 10

 in Obok_plugin/config.py on line 65 change
	QFileDialog.ShowDirsOnly to QFileDialog.Option.ShowDirsOnly

 in Obok_plugin/dialogs.py on line 412 and 451
     QTableWidgetItem.UserType to QTableWidgetItem.ItemType.UserType

**Comment by noDRM** [comment] 2022-07-13 13:42
Thanks agentxan, I've implemented these fixes on the master branch so this should fix #98. As for this bug, that's already fixed on master since #48 has been merged, which included a cleanup of all the crypto code. 

I should really get to releasing 10.0.3 ...

**Comment by chrisboeg** [comment] 2022-07-13 14:33
@noDRM: I can confirm it fixes the issue.

**Comment by noDRM** [comment] 2022-07-13 16:01
Thanks. 10.0.3 has just been released so there's no need to download from Github Actions or to manually package the plugin anymore.

**Closed by noDRM** 2022-07-13 16:01 UTC
