### ISSUE TITLE
Not working with rented books

### ISSUE THREAD

**Issue by Razodiac** [noDRM/DeDRM_tools#35] opened 2022-02-07 08:05 UTC
### Question / bug report

Hi, it seems that rented books have a different type of DRM or encryption that do not work with most DRM removal tools. It works with paid books, though.
https://imgur.com/a/IFKniGg
Most posts regarding rented books I can find online are from a couple of years ago: https://www.reddit.com/r/Piracy/comments/bm837l/guide_to_copy_kindle_content_to_pdf_using_calibre/emwthng/
I wonder if there is a workaround to it. You can experiment with rental trials on Amazon. 

### Which version of Calibre are you running?

5.36

### Which version of the DeDRM plugin are you running?

v10.0.2

### If applicable, which version of the Kindle software are you running?

1.31

**Comment by ElleKayEm** [comment] 2022-02-07 11:39
The problem isn't neccessarily rented or not.  The latest KFX format DRM cannot be removed purchased or not.  If a book can't be downloaded in the older formats or with Kindle for PC/Mac 1.26 or earlier, then it can't be decrypted at this time.  Rented textbooks are likely to be in this situation.  Here is a post for current methods of getting decryptable Amazon books:  https://www.mobileread.com/forums/showthread.php?t=283371

**Comment by romad275** [comment] 2022-02-07 16:46
It makes sense because if you remove DRM on books you DO NOT OWN, you are committing theft. Renting or checking out from a library an ebook does not transfer ownership. 

Sincerely,
Dennis B. Swaney

Cogito Ergo Mac

**Comment by ElleKayEm** [comment] 2022-02-07 17:13
Yes, that's undoubtably why many textbook publishers are insisting Amazon switch to this un-DeDRMable format for their books.  Inevitably leads to higher prices and possibly no rental option in the future.

**Comment by noDRM** [comment] 2022-03-19 14:12
Considering that this issue is related to general KFX issues, which I doubt are going to be supported by this plugin anytime soon, I'm going to close this issue as "wontfix", as I won't be working on KFX support.

**Closed by noDRM** 2022-03-19 14:12 UTC
